export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  INCREASE_PRODUCT_INSTOCK: "INCREASE_PRODUCT_INSTOCK",
  DECREASE_PRODUCT_INSTOCK: "DECREASE_PRODUCT_INSTOCK",
  OPEN_CART: "OPEN_CART",
  CLOSE_CART: "CLOSE_CART",
  SET_CART: "SET_CART",
};
